### PR TITLE
release 3.0.0

### PR DESCRIPTION
**Pull request by Hemantkumar-Chigadani**
Release first version with Quarkus 3

### CODE REVIEW

**Comment by gastaldi** [comment]
It's weird to have a 3.0.0, given that you don't have even a 1.0.0 yet, but it's your call

**Comment by gastaldi** [comment]
Do not release from a fork,  you need to trigger from a branch in this repository.

**Comment by gastaldi** [comment]
@Hemantkumar-Chigadani since you're a committer here, I'd recommend you to delete your fork and use branches in this repository during the development

**Comment by Hemantkumar-Chigadani** [comment]
> It's weird to have a 3.0.0, given that you don't have even a 1.0.0 yet, but it's your call

@gastaldi I thought there is relation b/w Major version to be same as that of quarkus Major version as convention. I can get it started from 1.0.0.

Quick question: How would be this extension appear under group-id  `io.quarkus.platform` ever?

**Comment by Hemantkumar-Chigadani** [comment]
Closing this PR in favour of #10

**Comment by gastaldi** [comment]
> Quick question: How would be this extension appear under group-id `io.quarkus.platform` ever?

Quarkiverse extensions are required to always be under the `io.quarkiverse.*` groupId and that will not change.

Now if you're asking to be part of the BOM, you need to be part of the https://github.com/quarkusio/quarkus-platform, which has a more rigorous process (which I personally don't think you need it)

**Pull request closed without merging**
